"use client"
import React, { useState } from 'react'
import useProject from '~/hooks/use-project'
import { Card, CardHeader, CardTitle, CardContent } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Textarea } from '~/components/ui/textarea'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '~/components/ui/dialog'
import Image from 'next/image'
import MarkdownPreview from '@uiw/react-markdown-preview';
import { useTheme } from 'next-themes';
import { api } from '~/trpc/react'
import { toast } from 'sonner'
import useRefetch from '~/hooks/use-refetch'
import { askQuestion } from './action'
import CodeRefrence from './code-refrence'
import { Compass, Send, Save, CheckCircle2, AlertCircle } from 'lucide-react'
import { Spinner } from '~/components/ui/spinner'
const AskQuestionCard = () => {
  const {project} = useProject()
  const { theme } = useTheme()
  const [question, setQuestion] = useState('')
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [filesReferences, setFilesReferences] = useState<{fileName: string, sourceCode: string, summary: string}[]>([])
  const [answer, setAnswer] = useState('')
  const saveAnswer= api.project.saveAnswer.useMutation()
  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    setAnswer('')
    setFilesReferences([])
    e.preventDefault()
    if (!project?.id) {
      toast.error("No project selected", {
        description: "Please select or create a project first"
      });
      return;
    }
    if (!question.trim()) {
      toast.error("Question cannot be empty", {
        description: "Please enter a question to get insights"
      });
      return;
    }
    setLoading(true)
    const loadingToast = toast.loading("Analyzing codebase...", {
      description: "Searching for relevant context and patterns"
    });
    try {
      const {output, filesRefrences} = await askQuestion(question, project.id)
      toast.dismiss(loadingToast);
      setOpen(true)
      setFilesReferences(filesRefrences)
      for await (const delta of output){
        if(delta){
          setAnswer((ans) => ans + delta)
        }
      }
      toast.success("Analysis complete", {
        description: "Your answer is ready",
        icon: <CheckCircle2 className="h-4 w-4" />
      });
    } catch (error) {
      toast.dismiss(loadingToast);
      console.error("Question analysis error:", error);
      toast.error("Unable to analyze question", {
        description: error instanceof Error ? error.message : "Please try again or rephrase your question",
        icon: <AlertCircle className="h-4 w-4" />,
        duration: 5000
      });
    } finally {
      setLoading(false);
    }
  }
  const refetch = useRefetch();
  return (
    <>
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-[80vw] max-h-[90vh]"> 
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle>
              <div className='flex items-center gap-3'>
                <div className="rounded-lg border border-border/60 bg-background p-2">
                  <Image src='/favicon.ico' alt='logo' width={24} height={24}/>
                </div>
                <div>
                  <h2 className='text-xl font-semibold'>Strategist answer</h2>
                  <p className="text-sm text-muted-foreground font-normal">Generated by GitWit Copilot</p>
                </div>
              </div>
            </DialogTitle>
            <Button 
              variant="outline" 
              size="sm"
              disabled={saveAnswer.isPending || !answer.trim()} 
              onClick={()=>{
                saveAnswer.mutate({
                  projectId: project!.id,
                  question,
                  answer,
                  filesRefrences: filesReferences
                },{
                  onSuccess:()=>{
                    toast.success('Answer archived successfully', {
                      description: "You can access it in the Q&A section",
                      icon: <CheckCircle2 className="h-4 w-4" />
                    });
                    refetch();
                  },
                  onError: (error) => {
                    console.error("Save answer error:", error);
                    toast.error("Unable to archive answer", {
                      description: error.message || "Please try again",
                      icon: <AlertCircle className="h-4 w-4" />
                    });
                  }
                })
              }}
              className="gap-2"
            >
              {saveAnswer.isPending ? (
                <>
                  <Spinner className="h-4 w-4 animate-spin-slow" />
                  Archiving…
                </>
              ) : (
                <>
                  <Save className="h-4 w-4" />
                  Archive answer
                </>
              )}
            </Button>
          </div>
        </DialogHeader>
        <div className="space-y-4 max-h-[60vh] overflow-y-auto">
          <div className="rounded-2xl border border-border/60 bg-card/80 p-4">
            {loading && !answer ? (
              <div className="flex items-center gap-3 py-8 text-muted-foreground">
                <Spinner className="h-5 w-5 animate-spin-slow" />
                <span className="text-sm">Synthesizing context from codebase...</span>
              </div>
            ) : (
              <MarkdownPreview 
                source={answer || "Waiting for response..."} 
                className='prose prose-sm dark:prose-invert max-w-none' 
                style={{ padding: '0', background: 'transparent' }}
                wrapperElement={{
                  "data-color-mode": theme === 'dark' ? 'dark' : 'light',
                }}
              />
            )}
          </div>
          {filesReferences.length > 0 && <CodeRefrence filesRefrences={filesReferences} />}
        </div>
        <Button 
          onClick={() => setOpen(false)} 
          variant="outline"
          className="w-full"
        >
          Close
        </Button>
      </DialogContent>
    </Dialog>
    <Card className='relative col-span-3 overflow-hidden border border-border/70 bg-card/70 shadow-lg shadow-primary/5'>
      <div className="absolute inset-x-6 top-0 h-0.5 bg-gradient-to-r from-transparent via-primary/40 to-transparent" />
      <CardHeader>
        <CardTitle className="flex items-center gap-3">
          <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-primary/12 text-primary">
            <Compass className="h-5 w-5" />
          </span>
          Strategic Q&A
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <form onSubmit={onSubmit} className="space-y-4">
          <div className="space-y-2">
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-muted-foreground">
              Share the scenario
            </p>
            <Textarea 
              className='min-h-[140px] resize-none border border-border/70 bg-background/80 px-4 py-3 text-sm leading-relaxed transition-shadow focus:border-primary focus:shadow-[0_0_0_2px_rgba(240,182,112,0.35)]' 
              placeholder='Example: “Compare the auth middleware with the new policy service.” or “What breaks if we sunset the CLI client?”' 
              value={question} 
              onChange={(e) => setQuestion(e.target.value)}
            />
          </div>
          <Button 
            type='submit' 
            disabled={loading || !question.trim()} 
            className="w-full gap-2 rounded-full transition-all"
          >
            {loading ? (
              <>
                <Spinner className="h-4 w-4 animate-spin-slow" />
                Synthesizing context…
              </>
            ) : (
              <>
                <Send className="h-4 w-4" />
                Ask GitWit
              </>
            )}
          </Button>
        </form>
      </CardContent>
    </Card>
    </>
  )
}
export default AskQuestionCard
